= Esercitazione su Servlet
Cristian Lucchesi <cristian.lucchesi@gmail.com>
2016-02-21
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true

== Preparazione ambiente di sviluppo

 * Java 8 -> http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
 * Editor Eclipse -> http://www.eclipse.org
 * Maven -> https://maven.apache.org
 * Database h2 -> http://www.h2database.com/
 * Apache Tomcat v8 -> http://tomcat.apache.org

== Installazione di Apache Tomcat
[%step]
 * Scaricare la versione 8 di Tomcat per il proprio sistema operativo
 * Scomprimere lo zip
 * Configurare Tomcat in Eclipse
 ** Aprire la _view_ "Servers"
 ** Tasto destro -> New -> Server
 ** Selezionare Tomcat v8.0 server -> Next
 ** Tomcat Installation Directory: -> Selezionare directory dove abbiamo scompresso Tomcat

== Esercitazione su Java e Servlet

Creazione di una applicazione web *anagrafica*.

Passi principali:
[%step]
* Creazione di un Dynamic Web Project + Maven
* Pagina Home del Progetto
* Utilizzo componenti del JDBC Tutorial
** DBConfig, Employee, EmployeeDao
* Lista del personale (Model + Controller + View)
* Visualizzazione dei dati
* Creazione del personale
* Modifica dei dati
* Funzionalità di ricerca del personale

== Creazione del progetto

[%step]
* in Eclipse -> file -> New -> Dynamic Web Project
** "Project Name:" -> "servlet-training"
** Verificare che il target Runtime sia Apache Tomcat
** Nella configurazione *Source folders on build path* -> rimuovere *src* ed aggiungere *src/main/java*
** In configurazione Web Module -> Selezionare *Generate web.xml deployment descriptor*
* Convertire il progetto in Maven Project
** Tasto destro sul progetto -> Configure -> Convert to Maven Project

== Creazione home page progetto

[%step]
* In WebContent creare una pagina HTML index.html
** contenente il titolo *Anagrafica personale*
** il messaggio <p>Benvenuti nell'anagrafica del personale!</p>
* nella _view_ *Servers* -> selezionare Tomcat v8 -> tasto destro *Add and remove*
** aggiungere il progetto *servlet-training*
** avviare Tomcat
* con il browser andare all'indirizzo http://localhost:8080/servlet-training

== Creazione HelloWorld servlet

[%step]
* creare un package tutorial.servlet
* creare una nuova Servlet -> File -> New -> Servlet
** package name: *tutorial.servlet*
** class name: *HelloWorldServlet*
** url mapping: */hello*
** method stub: *doGet*
* nel metodo doGet stampare l'html di base con h1 *Hello World !*
* controllare all'indirizzo http://localhost:8080/servlet-training/hello...

== Creazione HelloWorld servlet^(2)^

[[app-listing]]
[source,java]
.HelloWorldServlet.java
----
@WebServlet(name="Hello World Servlet", urlPatterns="/hello")
public class HelloWorldServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    response.setContentType("text/html; charset=utf-8");
    try (PrintWriter out = response.getWriter()) {
      out.println(
          "<html><head><title>Hello world" +
          "</title></head><body>");
      out.println(
          String.format("<h1> Hello %s ! </h1>", request.getParameter("name")));
      out.println("</body></html>");
    }
  }
}
----

== HelloWorldServlet con parametro

* stampare "Hello *name*" al posto di *Hello World !*
** al posto di *name* utilizzare il parametro *name" prelevato dalla request
* provare con l'indirizzo http://localhost:8080/servlet-training/hello?name=Cristian

== HelloWorldServlet con parametro^(2)^
[[app-listing]
[source,java]
.HelloWorldServlet.java
----
//...
@Override
public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
  response.setContentType("text/html; charset=utf-8");
  try (PrintWriter out = response.getWriter()) {
    out.println(
        "<html><head><title>Hello world" +
        "</title></head><body>");
    out.println(
        String.format("<h1> Hello %s ! </h1>", request.getParameter("name")));
    out.println("</body></html>");
  }
}
----

== Anagrafica via WEB - preparazione

[%step]
* aggiungere le dipendenze maven
** h2database, lombok (projectlombok), jstl (javax.servlet)
* copiare dal progetto di ieri le classi
** DBConfig, Employee, EmployeeDao

== Anagrafica via WEB - h2 load class
[source,java]
----
public static Connection getConnection() throws SQLException {
  try {
    //Necessario per far si che Tomcat carichi il driver JDBC correttamente
    Class.forName("org.h2.Driver");
  } catch (ClassNotFoundException e) {
    throw new RuntimeException("Driver h2 not found");
  }
  return DriverManager.getConnection(
      DBConfig.DB_URL, DBConfig.DB_USER, DBConfig.DB_PASSWORD);
}
----

== Lista Impiegati

[%step]
* creare una Servlet *PersonList*
** url mapping _persons/list_
** che utilizzi il metodo EmployeeDao::list
** che visualizzi la lista degli impiegati
* creare una jsp "persons/list.jsp"
** che mostri la lista degli impiegati
** hint:
*** RequestDispatcher view = request.getRequestDispatcher("/persons/list.jsp");
*** view.forward(request, response);

== Lista impiegati -> Servlet

[source,java]
----
@WebServlet("/persons/list")
public class PersonList extends HttpServlet {

  private final EmployeeDao employeeDao;

  public PersonList() {
    super();
    employeeDao = new EmployeeDao();
  }

  protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
    try {
      List<Employee> employees = employeeDao.list(Optional.empty());
      request.setAttribute("employees", employees);
      RequestDispatcher view = request.getRequestDispatcher("/persons/list.jsp");
      view.forward(request, response);
    } catch (SQLException e) {
      response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
  }
}
----

== Lista impiegati -> JSP

* creare la cartella WEBContent/ *persons*
* creare al suo interno la JSP *list.jsp*
* utilizzare `<c:forEach items="${employees}" var="e">`

== Lista impiegati -> JSP^(2)^

[[app-listing]]
[source,java]
.persons/list.jsp
----
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Elenco dipendenti</title>
</head>
<body>
  <h1>Anagrafica Dipendenti</h1>
  <h2>Elenco dipendenti</h2>
  <ul>
    <c:forEach items="${employees}" var="e">
       <li>
          ${e}
       </li>
    </c:forEach>
  </ul>
</body>
</html>
----

== Nuovo impiegato -> Form di creazione
[%step]
* creare la jsp */persons/blank.jsp*
* inserire una form con due campi input: name, surname
** i campi della form devono avere come valore ${name} e ${surname}
* il metodo deve essere *POST*, l'action *./new*

== Nuovo impiegato -> Form di creazione^(2)^
[[app-listing]]
[source,java]
./persons/blank.jsp
----
<!-- definizione html, body, h1..-->
<h2>Nuovo dipendente</h2>
<form action="./new" method="POST">
  <div>
    <label for="name">Nome</label>
    <input type="text" name="name" value="${name}" />
  </div>
  <div>
    <label for="name">Cognome</label>
    <input type="text" name="surname" value="${surname}" />
  </div>
  <div class="buttons">
    <input type="submit" name="submit" value="Salva" />
  </div>
</form>
<!-- chiusura body e html -->
----

== Servlet /persons/new
[%step]

* creare la servlet PersonNew
* con metodi doGet e doPost per implementare il rendering della form ed il salvataggio della persona
* url mapping */persons/new*
* nel metodo *doGet* fare il dispatching a */persons/blank.jsp*
* nel metodo *doPost* estrarre i parametri per name e surname
** in caso di errori (name o surname mancanti) mostrare ancora la JSP */persons/blank.jsp*
** in caso di successo salvare l'employee (utilizzando il DAO) e fare redirect a *./list*

== Servlet /persons/new doGet
[[app-listing]]
[source,java]
.PersonNew.java
----
@WebServlet("/persons/new")
public class PersonNew extends HttpServlet {

  private final EmployeeDao employeeDao;

  public PersonNew() {
    super();
    employeeDao = new EmployeeDao();
  }

  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    RequestDispatcher view = request.getRequestDispatcher("/persons/blank.jsp");
    view.forward(request, response);
  }
}
----

== Servlet /persons/new doPost

[[app-listing]]
[source,java]
.PersonNew.java
----
  protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    String name = request.getParameter("name");
    String surname = request.getParameter("surname");
    //Validazione dei parametri di ingresso
    if (name == null || name.equals("") || surname == null || surname.equals("")) {
      //TODO: inserire anche un messaggio di errore
      RequestDispatcher view = request.getRequestDispatcher("/persons/blank.jsp");
      view.forward(request, response);
      return;
    }
    try {
      employeeDao.persist(name, surname);
      response.sendRedirect("./list");
    } catch (SQLException e) {
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
  }
----

== Modifica dei dipendenti

* rendiamo ri-utilizzabile la form con i dati dell'Employee
** creare una jsp _form.jsp contenente i campi input
* creiamo una JSP */persons/edit.jsp* che importi la form precedente
** <c:import url="./_form.jsp" />
** con aggiunto un campo hidden per l'id dell'Employee

== Modifica dei dipendenti^(2)^

* creiamo una Servlet *PersonEdit*
* url mapping */persons/new*
* nel metodo *doGet* fare il dispatching a */persons/edit.jsp*
* nel metodo *doPost* estrarre i parametri per salvare l'Employee
** in caso di errori (name o surname mancanti) mostrare ancora la JSP */persons/edit.jsp*
** in caso di successo salvare l'employee (utilizzando il DAO) e fare redirect a *./list*

== Ri-uso form per Dipendente

* copiare il contenuto della form in questo nuovo file *_form.jsp*

[[app-listing]]
[source,java]
._form.html
----
<div>
  <label for="name">Nome</label>
  <input type="text" name="name" value="${name}" />
</div>
<div>
  <label for="name">Cognome</label>
  <input type="text" name="surname" value="${surname}" />
</div>
----

== Form di modifica Dipendente

[[app-listing]]
[source,java]
.edit.html
----
<!-- definizione html, body, ..-->
<h1>Modifica ${name} ${surname}</h1>
	
<form action="./edit" method="POST">
  <input type="hidden" name="id" value="${id}" />
  <c:import url="./_form.jsp" />
		
  <div class="buttons">
    <input type="submit" name="submit" value="Salva" />
  </div>		
</form>
<!-- chiusura body e html -->
----

== Servlet /persons/edit doGet
[[app-listing]]
[source,java]
.PersonEdit.java
----
  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
      RequestDispatcher view = request.getRequestDispatcher("/persons/edit.jsp");
      String id = request.getParameter("id");
      if (id == null || id.equals("")) {
        response.setStatus(HttpServletResponse.SC_NOT_FOUND);
        return;
      }
      try {
        Optional<Employee> employee =
            employeeDao.findById(Integer.parseInt(id));
        request.setAttribute("id", employee.get().getId());
        request.setAttribute("name", employee.get().getName());
        request.setAttribute("surname", employee.get().getSurname());
      } catch (NumberFormatException nfe) {
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
      } catch (SQLException e) {
        response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
      }
      view.forward(request, response);
  }
----

== Servlet /persons/new doPost

[[app-listing]]
[source,java]
.PersonEdit.java
----
  protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
      String name = request.getParameter("name");
      String surname = request.getParameter("surname");
      String id = request.getParameter("id");
      //Validazione dei parametri di ingresso
      if (id == null || id.equals("") || name == null || name.equals("")
          || surname == null || surname.equals("")) {
        //TODO: inserire anche un messaggio di errore
        RequestDispatcher view = request.getRequestDispatcher("/persons/edit.jsp");
        view.forward(request, response);
        return;
      }
      try {
        employeeDao.save(Employee.builder()
            .id(Integer.parseInt(id)).name(name).surname(surname).build());
        //Inserire un messaggi di evento completato con successo
        response.sendRedirect("./list");
      } catch (SQLException e) {
        response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
      }
  }
----

== Link alla modifica Dipendente

[[app-listing]]
[source,java]
./persons/list.jsp
----
  <c:forEach items="${employees}" var="e">
     <li>
       <a href="./edit?id=${e.id}">${e}</a>
     </li>
  </c:forEach>
----

* nella lista del personale inserire un link alla nuova funzionalità di modifica